services:
  #  postgres:
  #    image: postgres:alpine
  #    environment:
  #      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #      - POSTGRES_USER=${POSTGRES_USER}
  #      - POSTGRES_DB=${DATABASE_NAME}
  #    volumes:
  #      - ./data:/var/lib/postgresql/data
  ##    порты убрать в проде, доступ по внутренней сети docker
  #    ports:
  #      - "5432:5432"

  #  раскомментировать, если хотим смотреть таблицы
  #  adminer:
  #    image: adminer
  #    restart: always
  #    ports:
  #      - "8081:8080"
  #    depends_on:
  #      - db

  hds:
    #    build: .
    image: ghcr.io/itmind/goweek:main
    env_file:
      - .env
    ports:
      - "8000:1323"
    volumes:
      - ./data:/data
      #    depends_on:
      #      - db
